# Generated by Django 6.0.7 on 2026-08-04 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('group', models.CharField(choices=[('restaurant', 'Restaurant'), ('hotel', 'Hôtel'), ('attraction', 'Attraction')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripadvisor_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('price_level', models.CharField(blank=True, max_length=10)),
                ('horaires', models.JSONField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('cuisine', models.JSONField(blank=True, null=True)),
                ('styles', models.JSONField(blank=True, null=True)),
                ('groupes', models.JSONField(blank=True, null=True)),
                ('note_tripadvisor', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('nombre_reviews', models.IntegerField(default=0)),
                ('photo_count', models.IntegerField(default=0)),
                ('recompenses', models.JSONField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attractions', to='attractions.category')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='attractions.attraction')),
            ],
        ),
    ]
