# Generated by Django 6.0.7 on 2026-08-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='styles',
        ),
    ]
