# Generated by Django 6.0.7 on 2026-08-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('profile_type', models.CharField(choices=[('Local', 'Local'), ('Touriste', 'Touriste'), ('Professionnel', 'Pro')], max_length=50)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
