# Generated by Django 6.0.7 on 2026-08-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('Local', 'Local'), ('Touriste', 'Touriste'), ('Professionnel', 'Professionnel')], max_length=50),
        ),
    ]
